apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-sliu
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-mucs-tenant/rhtap-demo-app/hacbs-test-project-sliu@sha256:16a95a75a44445470ddcf28fe6d5c79d4a8f38ff729298bce15206ca944a28fa
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
