apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-sliu
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-mucs-tenant/rhtap-demo-app/hacbs-test-project-sliu@sha256:251b4bba85c3165a655517d7ce1daae8534877bbb623cb10eda93cb7041a6137
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
